import { useState } from "react";
import { OriginFlowChart } from "~/components/OriginFlowChart";
import { KIND_LABEL, ORIGIN_PRESETS, type OriginPreset } from "~/data/origin-flow";
import { LANGUAGE_LABEL } from "~/lib/language";
import type { Route } from "./+types/origin-flow";

type Measurement = { answer: string; preset: OriginPreset };
export function meta(_: Route.MetaArgs) { return [{ title: "Origin Flow — AI参照情報源の発信国" }]; }

export default function OriginFlow() {
  const [id, setId] = useState(ORIGIN_PRESETS[0].id); const [topic, setTopic] = useState(""); const [model, setModel] = useState("openai/gpt-4.1-mini");
  const [result, setResult] = useState<Measurement | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [ideal, setIdeal] = useState(false);
  const cached = ORIGIN_PRESETS.find((item) => item.id === id)!; const preset = result?.preset ?? cached;
  const total = preset.sources.reduce((sum, item) => sum + item.count, 0); const japan = preset.sources.filter((item) => item.country === "日本").reduce((sum, item) => sum + item.count, 0); const unknown = preset.sources.filter((item) => item.country === "不明").reduce((sum, item) => sum + item.count, 0); const overseas = total - japan - unknown;
  const referenced = preset.expected.filter((item) => preset.sources.some((source) => source.domain === item.domain)).length; const gap = preset.expected.length ? Math.round(100 * (1 - referenced / preset.expected.length)) : null;
  async function measure(event: React.FormEvent) { event.preventDefault(); if (!topic.trim() || !model.trim()) return; setLoading(true); setError(""); setResult(null); setIdeal(false); try { const response = await fetch("/api/measure", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ topic, model }) }); const data = await response.json() as Measurement & { error?: string }; if (!response.ok) throw new Error(data.error ?? "測定に失敗しました。"); setResult(data); } catch (reason) { setError(reason instanceof Error ? reason.message : "測定に失敗しました。"); } finally { setLoading(false); } }
  return <div className="origin-wrap"><header><p className="eyebrow">ORIGIN FLOW ／ AI参照情報源の発信国</p><h1>AIは、どこの情報を根拠にしたか。</h1><p className="lede">ナラティブを入力すると、Web検索付きAI回答と参照情報源の発信国・種別を表示します。</p></header>
    <form className="origin-measure" onSubmit={measure}><label htmlFor="topic">調べたいナラティブ・質問</label><textarea id="topic" value={topic} onChange={(event) => setTopic(event.target.value)} placeholder="例: 日本の災害時の避難情報は十分か" required /><label htmlFor="model">OpenRouter モデルID</label><input id="model" list="model-examples" value={model} onChange={(event) => setModel(event.target.value)} required /><datalist id="model-examples"><option value="openai/gpt-4.1-mini"/><option value="openai/gpt-5.2"/><option value="anthropic/claude-sonnet-4.6"/><option value="google/gemini-2.5-flash"/></datalist><button type="submit" disabled={loading}>{loading ? "Web検索・分類中…" : "測定する"}</button><p>OpenRouterで利用できる任意のモデルIDを指定できます。Web検索は最大20件です。入力した言語（日本語・英語・繁体字中国語・韓国語）に合わせてプロンプトを切り替えます。</p></form>
    {error && <p className="origin-error" role="alert">{error}</p>}{result?.answer && <section className="origin-answer"><h2>AIの回答</h2><p>{result.answer}</p></section>}
    <div className="origin-controls"><label>キャッシュ再生 <select value={id} onChange={(event) => { setId(event.target.value); setResult(null); setIdeal(false); }}>{ORIGIN_PRESETS.map((item) => <option key={item.id} value={item.id}>{item.topic}</option>)}</select></label><button type="button" aria-pressed={ideal} onClick={() => setIdeal(!ideal)}>{ideal ? "実測に戻す" : "本来あるべき姿"}</button></div>
    <p className="origin-notice"><b>{result ? "今回の測定結果。" : "キャッシュ済みデモデータ。"}</b> 回答モデル: {preset.model}{preset.classifierModel ? ` ／ 分類モデル: ${preset.classifierModel}` : ""} ／ {preset.runAt} ／ 検索クエリ: {preset.query}{preset.language ? ` ／ プロンプト言語: ${LANGUAGE_LABEL[preset.language]}` : ""}</p>
    <div className="origin-grid"><section className="origin-panel"><div className="origin-stats"><div><strong>{total}</strong><span>参照件数</span></div><div><strong>{total ? Math.round(japan / total * 100) : 0}%</strong><span>日本発</span></div><div><strong>{total ? Math.round(overseas / total * 100) : 0}%</strong><span>海外発</span></div></div><div className="origin-score"><strong>{gap ?? "—"}</strong><span>空白スコア<br/><small>{gap === null ? "想定一次情報源は未推定" : `想定一次情報源 ${referenced} / ${preset.expected.length} 件を参照`}</small></span></div><div className="origin-meter"><i className="jp" style={{ width: `${total ? japan / total * 100 : 0}%` }}/><i className="overseas" style={{ width: `${total ? overseas / total * 100 : 0}%` }}/><i className="unknown" style={{ width: `${total ? unknown / total * 100 : 0}%` }}/></div><div className="origin-meter-label"><span>日本 {total ? Math.round(japan / total * 100) : 0}%</span><span>海外 {total ? Math.round(overseas / total * 100) : 0}%</span><span>不明 {total ? Math.round(unknown / total * 100) : 0}%</span></div><OriginFlowChart preset={preset} ideal={ideal}/></section><aside className="origin-panel origin-side"><h2>空白判定</h2><p><b>{gap === null ? "一次情報源は今後推定します" : gap >= 50 ? "日本の一次情報に空白があります" : "一次情報源の参照を確認"}</b></p><p>{preset.expected.length ? `未参照: ${preset.expected.filter((item) => !preset.sources.some((source) => source.domain === item.domain)).map((item) => item.name).join("、")}` : "発信国はドメイン辞書に基づいて分類しています。"}</p><p className="origin-muted">TLDだけで国籍を断定せず、辞書外は「不明」として表示します。</p><p className="origin-muted">このツールは情報の真偽を判定しません。</p></aside><section className="origin-panel origin-sources"><h2>参照ソース</h2><table><thead><tr><th>媒体名 / ドメイン</th><th>発信国</th><th>種別</th><th>確度</th><th>件数</th></tr></thead><tbody>{preset.sources.map((source) => <tr key={source.domain}><td><b>{source.name}</b><br/><span>{source.domain}</span></td><td>{source.country}</td><td>{KIND_LABEL[source.kind]}</td><td>{source.confidence}</td><td>{source.count}</td></tr>)}</tbody></table></section></div></div>;
}
